### ISSUE TITLE
Directory 'contracts' empty

### ISSUE THREAD

**Issue by onekiloparsec** [tibastral/contrats-francais#29]
Je suis un peu embêté de rouvrir une issue (#22) de 2016... mais moi non plus, rien dans le répertoire contracts. Je suis sur macOS 10.13 / ruby 2.3

**Comment by onekiloparsec** [comment]
.. mais j'ai bien les .md complétés dans tmp/.

**Comment by tibastral** [comment]
Moi ça marche, je comprends pas


On 24 May 2018 at 14:47:04, Cédric Foellmi (notifications@github.com) wrote:

.. mais j'ai bien les .md complétés dans tmp/.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tibastral/contrats-francais/issues/29#issuecomment-391701633>,
or mute the thread

**Comment by brunto** [comment]
J'ai eu le même soucis et c'est un problème de version d'une lib qui génère les PDF

**Comment by tibastral** [comment]
Ok, mais comment reproduire ce bug ?


On 25 May 2018 at 11:29:59, Bruno Perles (notifications@github.com) wrote:

J'ai eu le même soucis et c'est un problème de version d'une lib qui génère
les PDF

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/tibastral/contrats-francais/issues/29#issuecomment-391997130>,
or mute the thread

**Comment by tibastral** [comment]
J'ai mis la branche development dans le source, vous me direz si ça vous convient.
